### ISSUE TITLE
Config used for paper results

### ISSUE THREAD

**Issue by patripfr** [pbias/lunet#4]
Hi, 
Is the example config given in this repo the same as used for the paper results? In the paper I could not find anything about the `pointnetize` part. However, in the config given here it is enabled. Could you give me some insight about this?

Thanks!

**Comment by pbias** [comment]
Hi,

The given config is indeed the one used for the paper results. The `pointnetize `part is simply used for data preparation. As the dataset used in the paper consists of range-images, the `pointnetize` function is used to transform the range-image in two matrices: one that is the points characteristics (a set of p_i, r_i), and the second one corresponds to the 3D coordinates of the 8-connected neighbors of each point (\bar{N}(p_i)). This satisfies the input presented in Figure 5, and is better detailed Section 3.3 of the article.

Hope that it helps :)

EDIT: And if you wonder about the `pointnet` setting in the config file, it simply enables or disable the 3D feature extraction module.

**Comment by patripfr** [comment]
Alright, that makes sense now :) Thanks!

**Comment by patripfr** [comment]
Hi, 
reopening because I just stumbled upon a line in your code that for me sounds confusing in regards to what's described in the article. In the article (\bar{N}(p_i)) is described as the set of neighbors in coordinates relative to p_i. However, [here](https://github.com/pbias/lunet/blob/master/data_loader.py#L172 ) the subtraction is commented out. Is this compensated somewhere else in the code or am I missing something here?
Thanks!

**Comment by pbias** [comment]
Hi !

You are not missing anything, and you are totally right. I'm afraid that I left this line commented after I produced the results of the Table 2 in the ablation study. Therefore it must be uncommented as it affects the results of the method (as discussed in the paper).

Thank you very much for pointing that out, I just pushed a new version with the uncommented line :)

**Comment by patripfr** [comment]
Glad we figured that out, closing then :)
